### ISSUE TITLE
iot模块webview中房间列表切换无法滑动问题

### ISSUE THREAD

**Issue by CharmanderG** [Rokid/RokidMobileSDKAndroidDemo#1]
iot模块webview中房间列表切换无法滑动

**Comment by shper** [comment]
这个问题分两种：
1、如果Webview 不在 ViewPager 里，是不会造成 滑动问题的，如果有问题，请检测自己的代码，有没有 touch 劫持 和冲突。
2、如果Webview 在 ViewPager 里，请设置 webview 的 OnTouchListener 来解决 touch 冲突，详情可以参考 Demo 工程的 SkillHomebaseFragment
