### ISSUE TITLE
android demo

### ISSUE THREAD

**Issue by xxnvzi** [Rokid/RokidMobileSDKAndroidDemo#6]
android demo打开智能家居这个页面一直显示加载中。➕按钮点击不了

**Comment by shper** [comment]
如果 使用 Demo 默认的 appkey 是正常的，如果替换成自己申请的，请确认 权限 和 帐号。

**Comment by xxnvzi** [comment]
您好。账号使用的是这个，请帮忙查看下。android demo打开智能家居这个页面一直显示加载中。➕按钮点击不了------------------------------------------------------------------发件人：Shper <notifications@github.com>发送时间：2018年3月14日(星期三) 14:30收件人：Rokid/RokidMobileSDKAndroidDemo <RokidMobileSDKAndroidDemo@noreply.github.com>抄　送：唐文飞 <tangwf@hicando.com>; Author <author@noreply.github.com>主　题：Re: [Rokid/RokidMobileSDKAndroidDemo] android demo (#6)
如果 使用 Demo 默认的 appkey 是正常的，如果替换成自己申请的，请确认 权限 和 帐号。—

**Comment by xxnvzi** [comment]
您好，我这边显示的日志如下。系统是android 5.0 的魅族
------------------------------------------------------------------发件人：唐文飞 <tangwf@hicando.com>发送时间：2018年3月14日(星期三) 14:47收件人：Rokid/RokidMobileSDKAndroidDemo <RokidMobileSDKAndroidDemo@noreply.github.com>; Rokid/RokidMobileSDKAndroidDemo <reply@reply.github.com>抄　送：Author <author@noreply.github.com>主　题：回复：[Rokid/RokidMobileSDKAndroidDemo] android demo (#6)
您好。账号使用的是这个，请帮忙查看下。android demo打开智能家居这个页面一直显示加载中。➕按钮点击不了------------------------------------------------------------------发件人：Shper <notifications@github.com>发送时间：2018年3月14日(星期三) 14:30收件人：Rokid/RokidMobileSDKAndroidDemo <RokidMobileSDKAndroidDemo@noreply.github.com>抄　送：唐文飞 <tangwf@hicando.com>; Author <author@noreply.github.com>主　题：Re: [Rokid/RokidMobileSDKAndroidDemo] android demo (#6)
如果 使用 Demo 默认的 appkey 是正常的，如果替换成自己申请的，请确认 权限 和 帐号。—
